logging:
  pattern:
    console: "[Kafka Order] %clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

server:
  port: 9001

spring:
  main:
    banner-mode: OFF
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:authuser
  jpa:
    open-in-view: false